#pragma config(Sensor, in1,    drPot,          sensorPotentiometer)
#pragma config(Sensor, dgtl1,  encR,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encL,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  gripperBottom,  sensorDigitalOut)
#pragma config(Sensor, dgtl7,  baseL,          sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  baseR,          sensorQuadEncoder)
#pragma config(Sensor, dgtl11, limitDR,        sensorTouch)
#pragma config(Sensor, dgtl12, limitArms,      sensorTouch)
#pragma config(Motor,  port1,           armL,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           gripperBottom, tmotorNone, openLoop)
#pragma config(Motor,  port3,           rbBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rfBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lbBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lfBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           DRLU,          tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           DRRU,          tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          armR,          tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// Status para cada proceso
float armStat; // status de los brazos de arriba
float drStat; // status del double reverse
float baseStat;
bool topOpen;
bool bottomOpen;

// Targets para procesos
float baseTarget;
int drTarget; // target del double reverse
float armTarget;

//Speeds de los procesos
float drSpeed;
float armSpeed;
float baseSpeed;

// VexRT(Ch2)*(SensorValue(limit1 + hold)*(SensorValue(limit2);

// Add Stacking System
// using light sensrs para saber cuantos conos tiene

//Cambiar los dos encoders del chain bar por dos limits

//?
void setTopGripper(bool open){
	topOpen = open;
}

void arm(float speed)
{
	//Assumption: Arms goes up with both motors set to positive values
	motor[armL] = speed;
	motor[armR] = speed;
}
void arm(float speedL, float speedR)
{
	//Assumption: Arms goes up with both motors set to positive values
	motor[armL] = speedL;
	motor[armR] = speedR;
}

void armX(float speed)
{
	const float k = 0.50;
	const int encDif = 2;
	int Q = (SensorValue(encL)-SensorValue(encR)); // Andres Comment - Is sensor drift a problem?

	if(Q <= encDif && Q >=-encDif)
	{
		arm(speed);
	}
	else if(Q > encDif)
	{
		if(speed >= 0)
			arm(k*speed,speed);
		else
			arm(speed,k*speed);
	}
	else
	{
		if(speed >= 0)
			arm(speed,k*speed);
		else
			arm(k*speed,speed);
	}
}

//Proceso de brazos
task setArm{ // Andres Comment - Sets arm based on only one side
	while(SensorValue(encR) < armTarget){
		armX(armSpeed);
		armStat = (SensorValue(encR) / armTarget);	//set el porcentaje
	}
	arm(0);
}

//Proceso de double reverse y brazos
void setDR (){

    if(SensorValue(drPot) < drTarget){
    	while(SensorValue(drPot) < drTarget){
    		motor[DRLU] = drSpeed;
    		motor[DRRU] = drSpeed;

    		// anade sube el chain bar tambien
    		drStat = (SensorValue(drPot) / drTarget);  //set el porcentaje
    	}
    }
    //sino, es mayor y hay que bajar el dr
    else{
        while(SensorValue(drPot) > drTarget){
            motor[DRLU] = -1 * drSpeed;
    				motor[DRRU] = -1 * drSpeed;

            // anade sube el chain bar tambien
			      drStat = (drTarget / SensorValue(drPot));
        }
    }
   	motor[DRLU] = 0;
    motor[DRRU] = 0;
}

// Procesio de base
task moveBase
	{

		SensorValue(baseL) = 0;
		SensorValue(baseR) = 0;

		const float k = 0.50;
		const int encDif = 2;
		int Q = (SensorValue(baseL)-SensorValue(baseR));

		while(SensorValue(baseL) < baseTarget){ // Andres Comment - Target based only on left

			if(Q <= encDif && Q >=-encDif)
			{
				motor[rbBase] = baseSpeed;
				motor[rfBase] = baseSpeed;
				motor[lbBase] = baseSpeed;
				motor[lfBase] = baseSpeed;
			}
			else if(Q > encDif)
			{
				if(baseSpeed >= 0){
					motor[rbBase] = baseSpeed;
					motor[rfBase] = baseSpeed;
					motor[lbBase] = baseSpeed*k;
					motor[lfBase] = baseSpeed*k;
				}
				else{
					motor[rbBase] = baseSpeed*k;
					motor[rfBase] = baseSpeed*k;
					motor[lbBase] = baseSpeed;
					motor[lfBase] = baseSpeed;

				}
			}
			//moving back
			else
			{
				if(baseSpeed >= 0){
					motor[rbBase] = baseSpeed*k;
					motor[rfBase] = baseSpeed*k;
					motor[lbBase] = baseSpeed;
					motor[lfBase] = baseSpeed;
				}
				else{
					motor[rbBase] = baseSpeed;
					motor[rfBase] = baseSpeed;
					motor[lbBase] = baseSpeed*k;
					motor[lfBase] = baseSpeed*k;
				}
			}

			baseStat = SensorValue(encL) / baseTarget;
	}
	motor[rbBase] = 0;
	motor[rfBase] = 0;
	motor[lbBase] = 0;
	motor[lfBase] = 0;
	}


// Brazos y base para skills
void BaseArm(int armT,int baseT, float armS, float baseS) {
	writeDebugStreamLine("Starting BaseArm task");
	float origArmSpeed = armS;
	float origBaseSpeed = baseS;

	armTarget = armT;
	baseTarget = baseT;
	armSpeed = armS;
	baseSpeed = baseS;

	armStat = 0;
	baseStat = 0;

	startTask(setArm);
	startTask(moveBase);

	while(armStat < 1 || baseStat < 1){
			writeDebugStreamLine("Arm Status: %f",armStat);
			writeDebugStreamLine("Base Status: %f",baseStat);
			// (int)armSpeed == (int)origArmSpeed) - para no seguir bajando la velocidad del brazo
			if((armStat - baseStat) > 0.20 && (int)armSpeed == (int)origArmSpeed){
				armSpeed *= 0.50;
				writeDebugStreamLine("Arm Speed: %f",armSpeed);

			}
			else if((baseStat - armStat) > 0.20){
					baseSpeed *= 0.50;
			}
			else{
				armSpeed = origArmSpeed;
				baseSpeed = origBaseSpeed;
			}
	}
	armSpeed = 0;
	baseSpeed = 0;
	writeDebugStreamLine("Ending BaseArm task");
}



// Brazos y base para autonomo
//Recibe un target para la base - en ticks y
//un numero para el potenciometro para lo brazos
//debo saber el progreso de los brazos?
void BaseBothArms(int armT,int baseT, float armS, float baseS) {
	writeDebugStreamLine("Starting BaseBothArms task");
	float origDrSpeed = armS;
	float origBaseSpeed = baseS;

	baseTarget = baseT;
	drTarget = armT;
	drSpeed = armS;
	baseSpeed = baseS;

	drStat = 0;
	baseStat = 0;

	//startTask(setDR);
	startTask(moveBase);

	while(drStat < 1 || baseStat < 1){
			writeDebugStreamLine("Double Reverse Status: %f",armStat);
			writeDebugStreamLine("Base Status: %f",baseStat);
			// (int)armSpeed == (int)origArmSpeed) - para no seguir bajando la velocidad del brazo
			if((drStat - baseStat) > 0.20 && (int)armSpeed == (int)origDrSpeed){
				drSpeed *= 0.50;
				writeDebugStreamLine("Double Reverse Speed: %f",drSpeed);

			}
			else if((baseStat - drStat) > 0.20){
					baseSpeed *= 0.50;
			}
			else{
				drSpeed = origDrSpeed;
				baseSpeed = origBaseSpeed;
			}
	}
	drSpeed = 0;
	baseSpeed = 0;
	writeDebugStreamLine("Ending BaseArm task");
}



/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.


		SensorValue(encR) = 0;
		SensorValue(encL) = 0;
		SensorValue(baseR) = 0;
		SensorValue(baseL) = 0;

		bottomOpen = false;
		topOpen = false;

		clearDebugStream();

		bStopTasksBetweenModes = true; //  ???

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

//la diagonal creciente esta invertida

/*
		motor[DRLU] = 75;
    motor[DRRU] = 75;
		wait1Msec(3000);
	  motor[DRLU] = 0;
    motor[DRRU] = 0;
*/
  // Remove this function call once you have "real" code.
  //AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
//2055 - arriba, maximo del reverse bar
//245 - abajo, minimo del double reverse
task usercontrol()
{
  // User control code here, inside the loop
  /*
	drTarget = 1000;
	drSpeed = 75;

	setDR();

	drTarget = 500;
	drSpeed = 75;

	setDR();

	*/
	// This is the main execution loop for the user control program.
  // Each time through the loop your program should update motor + servo
  // values based on feedback from the joysticks.

  // ........................................................................
  // Insert user code here. This is where you use the joystick values to
  // update your motors, etc.
  // ........................................................................

  // Remove this function call once you have "real" code.
  //UserControlCodePlaceholderForTesting();

	//
	float hold = 15/127;

	// Movimiento de la base
	motor[rfBase]= vexRT[Ch3] - vexRT[Ch4];
	motor[rbBase]= vexRT[Ch3] - vexRT[Ch4];
	motor[lfBase]= vexRT[Ch3] + vexRT[Ch4];
	motor[lbBase]= vexRT[Ch3] + vexRT[Ch4];

	//Movimiento del double reverse
	// pada cuando llegue a su limite CH2

	//Double Reverse LEFT/RIGHT UP/DOWN
	motor[DRLU] = vexRT(Ch2)*(SensorValue(limitDR) + hold); // why? *SensorValue(limitArms);
	motor[DRRU] = vexRT(Ch2)*(SensorValue(limitDR) + hold); //      *SensorValue(limitArms);

	//false = in
	//true = out
	if(vexRT[Btn6U])
	{
		setTopGripper(false);
	}
	if(vexRT[Btn6D])
	{
		setTopGripper(true);
	}

	// Abre/cierra gripper de abajo
	if(vexRT[Btn5U])
	{
		//chain bar = ch2;
		motor[armL] = vexRT(Ch2);
		motor[armR] = vexRT(Ch2);
		//control
	}
	if(vexRT[Btn5D])
	{
		//mobile goal = ch2
		motor[gripperBottom] = vexRT(Ch2);
	}
}
