#pragma config(Sensor, dgtl1,  encLeft,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encRight,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  coneSonar,      sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  baseSonar,      sensorSONAR_cm)
#pragma config(Motor,  port1,           chainbarLeft,  tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rollers,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           elevationLeft, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           elevationRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           moGoGripper,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           backLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           backRight,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          chainbarRight, tmotorVex393_HBridge, openLoop)
#pragma config(Sensor, in1,    potElevation,   sensorPotentiometer)
#pragma config(Sensor, in2,    potGripper,     sensorPotentiometer)
#pragma config(Sensor, in3,    potChainbar,    sensorPotentiometer)
#pragma config(Sensor, in4,    gyroBase,       sensorGyro)
#pragma config(Sensor, in5,    accBase,        sensorAccelerometer)
#pragma config(Sensor, in6,    light,          sensorNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

#pragma platform(VEX2)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


//*********************************************************************************************
//			Includes
//*********************************************************************************************

#include "BNSLib.h";

#define STOP 0
#define CHAINBAR_HORIZONTAL 1900
#define CHAINBAR_VERTICAL 3570
#define CHAINBAR_DOWN 1440
#define MAX_CONE_DISTANCE 24
#define MAX_ELEVATION 1980
#define MAX_CONES 17
#define DOWN_DR 410
#define DROP_MOGO 2210
#define GET_MOGO 330
#define VERTICAL_MOGO 1060
#define SIDE_BAR 850
#define SONAR_LIST 80

int cones = 0;
int heights[13] = {-100,-50,0,60,20,160,220,330,455,560,735,860,MAX_ELEVATION};

//*********************************************************************************************
//			Setters
//*********************************************************************************************

void setBase(int speed){
	motor[frontLeft] = speed;
	motor[frontRight] = speed;
	motor[backLeft] = speed;
	motor[backRight] = speed;
}
void setBaseOffset(int speed, int offset){
	motor[frontLeft] = speed - offset;
	motor[frontRight] = speed + offset;
	motor[backLeft] = speed - offset;
	motor[backRight] = speed + offset;
}
void setBase(int speedL, int speedR){
	motor[frontLeft] = speedL;
	motor[frontRight] = speedR;
	motor[backLeft] = speedL;
	motor[backRight] = speedR;
}
void setRollers(int speed){
	motor[rollers] = speed;
}
void setRollers(int speed, int time_ms){
	setRollers(speed);
	wait1Msec(time_ms);
	setRollers(STOP);
}
void setMOGOGripper(int speed){
	motor[moGoGripper] = speed;
}
void setElevation(int speed){
	motor[elevationLeft] = speed;
	motor[elevationRight] = speed;
}
void setChainbar(int speed){
	motor[chainbarLeft] = speed;
	motor[chainbarRight]= speed;
}

//*********************************************************************************************
//			Base Functions
//*********************************************************************************************

// This variables for the ecnoders and counter fore the PID.
int encoderL, encoderR, counter;

// Function to move the robot to the front or back.
void moveBase(int speed)
{
	setBase(speed);
}

// Funtion to correct the aligment of the robot when move to the front or back.
void moveBase(int speed, int offset)
{
	setBaseOffset(speed, offset);
}

// Rotate the base clockwise or counter-clockwise.
void rotateBase(int speed)
{
	setBase(-speed, speed);
}

// Stop moving the robot.
void stopBase()
{
	setBase(0);
}

// Convert the distance of ticks (the value of the encoder) in inches.
float ticksToInches(int ticks)
{
	float inches = ticks*((2.75*PI)/360.0)/0.9;
	return inches;
}

float inchesToTicks(int inches)
{
	float ticks = inches*(360.0/(2.75*PI))*0.9;
	return ticks;
}


// Move the base to the front. Request the distance for know how much need to move,
// the variable time is the maximun time for wait to the movement to
// prevent keep going infinitely the task if the robot can´t move and
// finally, the variable factor to reduce the velocity of the robot.
// Note: The distance in inches.
void moveBaseWithFactor(int distance, int time, float factor){
	distance = inchesToTicks(distance);
	writeDebugStreamLine("Start moveBaseFront");
	writeDebugStreamLine("Target distance = %d", distance);
	int encoderAvg = 0;
	encoderR = 0;
	encoderL = 0;
	float initialGyro = SensorValue[gyroBase], actualGyro = initialGyro;
	writeDebugStreamLine("Initial Gyro Position = %f", initialGyro);
	int startEncoderValueR = SensorValue[encRight];
	int startEncoderValueL = SensorValue[encLeft];
	bool atPos=false;
	float pidMovResult;
	//float pidStraightResult;
	counter = 0;

	PID pidMovement;
	//PID pidStraight;
	PIDInit(&pidMovement, 0.3, 0, 1.5); // Set P, I, and D constants
	//PIDInit(&pidStraight, 2, 0, 0.3);//Set constants for driving straight

	clearTimer(T1);
	int timer = T1;
	while(!atPos && timer < time){
		encoderR = (SensorValue[encRight] - startEncoderValueR);
		encoderL = SensorValue[encLeft] - startEncoderValueL;
		encoderAvg = (encoderR+encoderL)/2;
		writeDebugStreamLine("encR = %d\tencL = %d", encoderR, encoderL);
		pidMovResult = PIDCompute(&pidMovement, distance - encoderAvg);
		//pidStraightResult = PIDCompute(&pidStraight, initialGyro - actualGyro);
		//writeDebugStreamLine("Actual Gyro Position = %f   PID = %f", actualGyro, pidStraightResult);
		moveBase(pidMovResult);
		if (abs(encoderAvg-distance)<2)
			counter++;
		if (counter >= 4)
			atPos = true;
		timer = time1[T1];
		wait1Msec(25);
		actualGyro = SensorValue[gyroBase];
	}
	moveBase(0);
	writeDebugStreamLine("Encoder at position = %d", encoderAvg);
}

// Move the base to the back. Request the distance for know how much need to move,
// the variable time is the maximun time for wait to the movement to
// prevent keep going infinitely the task if the robot can´t move and
// finally, the variable factor to reduce the velocity of the robot.
// Note: The distance in inches.
void moveBaseBack(int distance, int time, int slowFactor)
{
	distance = inchesToTicks(distance);

	writeDebugStreamLine("Start moveBaseFront");
	writeDebugStreamLine("Target distance = %d", distance);

	int encoderAvg = 0;
	encoderR = 0;
	encoderL = 0;
	int startEncoderValueR = SensorValue[encRight];
	int startEncoderValueL = SensorValue[encLeft];
	bool atPos=false;
	float pidMovResult, pidStraightResult;
	counter = 0;

	PID pidMovement;
	//PID pidStraight;
	PIDInit(&pidMovement, 0.3, 0, 1.5); // Set P, I, and D constants
	//PIDInit(&pidStraight, 0.5, 0, 0);//Set constants for driving straight

	clearTimer(T1);
	int timer = T1;

	while(!atPos && timer < time)
	{
		encoderR = abs(SensorValue[encRight] - startEncoderValueR);
		encoderL = abs(SensorValue[encLeft] - startEncoderValueL);
		writeDebugStreamLine("encoder derecho = %d", encoderR);
		writeDebugStreamLine("encoder izquierdo = %d", encoderL);
		encoderAvg = (encoderR+encoderL)/2;
		pidMovResult = PIDCompute(&pidMovement, distance - encoderAvg);
		//pidStraightResult = PIDCompute(&pidStraight, encoderL - encoderR);
		pidMovResult = pidMovResult >  127 ? 127 : pidMovResult;

		moveBase(-pidMovResult);

		if (abs(encoderAvg-distance)<2)
			counter++;
		if (counter >= 4)
			atPos = true;
		timer = time1[T1];
		wait1Msec(25);
	}
	stopBase();
	writeDebugStreamLine("Encoder at position = %d", encoderAvg);
}

// Default values for configure the gyro.
float gyroAngle, tempAngle;
int offsetAngle = 0;

// Configure the default values of the gyro.
void setOffsetAngle (int angle){
	offsetAngle = angle;
}

// Task for get the value of the gyro
task getGyro {
	while(1){
		tempAngle = (SensorValue[gyroBase]/10.0 + offsetAngle)%360;//Offset can be changed with function.
		if(tempAngle<0){
			gyroAngle=tempAngle+360;
		}
		else{
			gyroAngle=tempAngle;
		}
		writeDebugStreamLine("gyro = %f", gyroAngle);
		wait1Msec(10);																	 //Default is 90.
	}
}


void rotateToAngle(float targetAngle, int time,float P, float I, float D){
	writeDebugStreamLine("Start rotateToAngle");
	writeDebugStreamLine("Target angle = %f", targetAngle);
	bool atGyro=false, isCW=false;
	float pidGyroResult, offset, currAngle;
	int counter = 0;

	// Change negative target angle to 0-360 range
	if(targetAngle < 0){
		targetAngle += 360;
	}

	// Set offset as current angle
	offset = gyroAngle;

	// Offset target
	targetAngle -= offset;
	if(targetAngle < 0)
		targetAngle += 360;

	// Is CW
	if(targetAngle > 180)
		isCW = true;

	// PID Constant cases
	PID pidGyro;
	PIDInit(&pidGyro, P,I,D); // Set P, I, and D constants
	// giro de 30 PIDInit(&pidGyro, 1.3, 0.3, 4); // Set P, I, and D constants
	clearTimer(T1);
	while(!atGyro && time1[T1] < time){
		// Calculate current angle
		currAngle = gyroAngle - offset;
		if(currAngle < 0)
			currAngle += 360;
		if(isCW && currAngle < 180) // Un poquito de marron
			currAngle = 360;
		writeDebugStreamLine("Current angle = %f", currAngle);

		// Calculate error
		float error = targetAngle - currAngle;
		writeDebugStreamLine("error=%f",error);

		// Compute PID
		pidGyroResult = PIDCompute(&pidGyro, error);
		rotateBase(pidGyroResult);

		// Condition to end
		if (abs(gyroAngle-targetAngle)<1)
			counter++;
		if (counter > 100)
			atGyro = true;
		wait1Msec(1);
	}
	writeDebugStreamLine("Final angle = %f", gyroAngle);
	stopBase();
}

void rotateToAngle(float targetAngle, int time){
	rotateToAngle(targetAngle, time, 0.25, 0, 1.8);
}


// Rotate the base to one side. The variable time is the maximun time for wait to the rotation to
// prevent keep going infinitely the task if the robot can´t rotate.
// The variable angle is for the amount of angle to rotate.
void rotateThisAngle(float angle, int time){
	writeDebugStreamLine("Start rotateThisAngle");
	writeDebugStreamLine("Target angle = %f", angle);
	bool atGyro = false;
	float pidGyroResult;
	counter = 0;

	PID pidGyro;
	PIDInit(&pidGyro, 0.3, 0, 0.4); // Set P, I, and D constants

	angle = (gyroAngle + angle)%360;

	clearTimer(T1);
	int timer = time1[T1];
	while(!atGyro && timer < time){
		pidGyroResult = PIDCompute(&pidGyro, angle - gyroAngle);
		rotateBase(15*pidGyroResult);
		if (abs(gyroAngle-angle)<2)
			counter++;
		if (counter > 3)
			atGyro = true;
		timer = time1[T1];
		wait1Msec(20);
	}
	stopBase();
}

void moveBase (int distance, int speed) {
	while(SensorValue(encLeft)<distance && SensorValue(encRight)) {
		if(encLeft == encRight) {
			setBase(speed);
		}
		else if(encLeft > encRight){
			setBase(speed*0.90, speed);
		}
		else{
			setBase(speed, speed*0.90);
		}
	}
}

void baseControl(void){
	setBase(vexRT(Ch3) + vexRT(Ch4),vexRT(Ch3) - vexRT(Ch4));
}

void rollerControl(){
	if(vexRT(Btn6U)){
		setRollers(127);
	}
	else if(vexRT(Btn6D)){
		setRollers(-127);
	}
	else{
		setRollers(15);
	}
}

void moGoControl(void){
	if(vexRT(Btn8R)){
		setMOGOGripper(127);
	}
	else if(vexRT(Btn8L)){
		setMOGOGripper(-127);
	}
	else{
		setMOGOGripper(STOP);
	}
}

void chainbarHold(void){
	if(SensorValue(potChainbar) > CHAINBAR_HORIZONTAL){
		setChainbar(-20);
	}
	else if(SensorValue(potChainbar) < CHAINBAR_HORIZONTAL){
		setChainbar(20);
	}
	else{
		setChainbar(STOP);
	}
}
void elevationHold(){
	setElevation(17);
}

void elevationControl(void){
	setElevation(vexRT(Ch2));
}

void setPositionCB(int angle){
	if(SensorValue[potChainbar] < angle)
	{
		while(SensorValue[potChainbar] < angle)
		{
			setChainbar(127);
			baseControl();
			elevationControl();
		}
	}
	else
	{
		while(SensorValue(potChainbar)>angle)
		{
			setChainbar(-127);
			baseControl();
			elevationControl();
		}
	}
	setChainbar(15);
	baseControl();
	elevationControl();
}

void setPositionCBHappy(int angle){
	if(SensorValue[potChainbar] < angle)
	{
		while(SensorValue[potChainbar] < angle)
		{
			setChainbar(127);
			baseControl();
		}
	}
	else
	{
		while(SensorValue(potChainbar)>angle)
		{
			setChainbar(-127);
			baseControl();
		}
	}
	if(angle == CHAINBAR_DOWN) setChainbar(-15);
	else setChainbar(15);
	baseControl();
}

void chainbarControl(){
	if(vexRT(Btn8U)){
		//setChainbar(127);
		baseControl();
		setPositionCB(CHAINBAR_VERTICAL);
		setChainbar(15);
		//setElevation(10);
	}
	else if(vexRT(Btn8D)){
		//setChainbar(-127);
		baseControl();
		setPositionCB(CHAINBAR_DOWN);
		setChainbar(0);
		//setElevation(10);
	}
	else{
		setChainbar(10);
	}
}

void setPositionDR(int angle){
	clearTimer(T2);
	if(SensorValue[potElevation] < angle)
	{
		while(SensorValue[potElevation] < angle && time1(T2) < 3000)
		{
			setElevation(127);
		}
	}
	else
	{
		while(SensorValue(potElevation)>angle && time1(T2) < 3000)
		{
			setElevation(-127);
		}
	}
	elevationHold();
}

void setPositionMogo(int angle){
	clearTimer(T2);
	if(SensorValue[potGripper] < angle)
	{
		while(SensorValue[potGripper] < angle && time1(T2) < 1000)
		{
			setMOGOGripper(127);
		}
	}
	else
	{
		while(SensorValue(potGripper)>angle && time1(T2) < 1000)
		{
			setMOGOGripper(-127);
		}
	}
	setMOGOGripper(0);
}


void bubbleSort(int *array){
	bool swapped = true;
	while(swapped){
		swapped = false;
		for(int i = 1	; i < SONAR_LIST; i++){
			if(array[i-1] > array[i]){
				int temp = array[i];
				array[i] = array[i-1];
				array[i-1] = temp;
				swapped = true;
			}
		}
	}
}

bool notThere(int *array){
	bubbleSort(array);
	int median = array[floor(SONAR_LIST/2)];
	if(median < MAX_CONE_DISTANCE)
		return true;
	return false;
}

bool neg(int a,int b, int c, int d, int e){
	if(a == -1 || b == -1 || c == -1 || d == -1 || e == -1) return true;
	return false;
}

bool sonarElevation(void){
	int array[SONAR_LIST];
	for(int i = 0; i < SONAR_LIST; i++){
		array[i] = SensorValue(coneSonar);
	}
	while(notThere(array)){
		//writeDebugStreamLine("Sonar = %d", SensorValue[coneSonar]);
		setElevation(127);
		if(SensorValue(potElevation) > MAX_ELEVATION-10){//Worst Case
			elevationHold();
			return true;
		}
		for(int i = 0; i < SONAR_LIST; i++){
			array[i] = SensorValue(coneSonar);
			//writeDebugStreamLine("TEMP %d = %d",i+1,array[i]);
		}


	}
	elevationHold();
	return false;
}

void triggerHappy(void){
	setPositionCB(CHAINBAR_DOWN);
	sonarElevation();
	setPositionCBHappy(CHAINBAR_VERTICAL);
	setChainbar(25);
	wait1Msec(400);
	setRollers(-127, 300);
	wait1Msec(100);//Let the Cone Settle
	setPositionCBHappy(CHAINBAR_HORIZONTAL);
	setChainbar(25);
	setPositionDR(DOWN_DR+75);
	wait1Msec(100);
	setChainbar(0);
}

void triggerHappyAuto(void){
	sonarElevation();
	setPositionCBHappy(CHAINBAR_VERTICAL);
	setChainbar(25);
	wait1Msec(400);
	setRollers(-127, 250);
	wait1Msec(100);//Let the Cone Settle
	setPositionCBHappy(CHAINBAR_DOWN);
	setPositionDR(DOWN_DR+350);
}

void triggerHappySide(void){
	setPositionDR(heights[cones]+SIDE_BAR);
	setPositionCBHappy(CHAINBAR_VERTICAL);
	writeDebugStreamLine("%d",SensorValue(potElevation)-DOWN_DR);
	setChainbar(15);
	wait1Msec(290 + 10*cones);//Let the Cone Settle
	setRollers(-127, 200);
	wait1Msec(300);//Let the Cone Settle
	setPositionCBHappy(CHAINBAR_DOWN);
}
void triggerHappyHold(void){
	setPositionDR(heights[cones]+SIDE_BAR);
	setPositionCBHappy(CHAINBAR_VERTICAL);
	writeDebugStreamLine("%d",SensorValue(potElevation)-DOWN_DR);
	setChainbar(15);
	wait1Msec(300 + 10*cones);//Let the Cone Settle
	setRollers(-127, 200);
	wait1Msec(300);//Let the Cone Settle
	setPositionDR(heights[cones]+SIDE_BAR-40);
	//setPositionCBHappy(CHAINBAR_DOWN);
}

void getConeFromSide(int side_bar_offset){
	setRollers(127);
	setPositionDR(SIDE_BAR+side_bar_offset);
	setPositionCB(CHAINBAR_DOWN);
	setRollers(10);
	triggerHappySide();
}

void getConeAndHold(){
	setRollers(127);
	setPositionDR(SIDE_BAR);
	setPositionCB(CHAINBAR_DOWN);
	setRollers(10);
	triggerHappyHold();
}

void getConeFromSide(){
	getConeFromSide(0);
}

void genericControl(void){
	baseControl();
	elevationControl();
	rollerControl();
	chainbarControl();
	moGoControl();
	//if(vexRT(Btn5U)) triggerHappy();
}

void init()
{
	BNS();

	//Initialize Gyro
	SensorType[gyroBase] = sensorNone;
	wait1Msec(1000);
	SensorType[gyroBase] = sensorGyro;
	wait1Msec(2000);
	//End Initialize Gyro

	SensorValue[encRight] = 0;
	SensorValue[encLeft] = 0;

	startTask(getGyro);

	clearDebugStream();
}

void moveBaseUntil(int distance,int time){
	clearTimer(T1);
	int timer = T1;
	setChainbar(15);
	if(SensorValue(baseSonar) > distance)
	{
		while(SensorValue(baseSonar) > distance  && timer < time){
			writeDebugStreamLine("%d\n",SensorValue(baseSonar));
			moveBase(127);
			timer = time1[T1];
		}
		moveBase(-10);
	}
	else
	{
		while(SensorValue(baseSonar) < distance  && timer < time){
			writeDebugStreamLine("%d\n",SensorValue(baseSonar));
			moveBase(-127);
			timer = time1[T1];
		}
		moveBase(10);
	}
	wait1Msec(100);
	moveBase(0);
	writeDebugStreamLine("Sonar = %d", SensorValue(baseSonar));
}

void auto_test(){
	setRollers(30);
	setPositionDR(MAX_ELEVATION-800);
	setChainbar(-127);
	wait1Msec(700);
	setChainbar(0);
	// Crayola cone
	moveBaseWithFactor(5,500,1);
	wait1Msec(200);
	setRollers(-127,200);
	// First cone
	moveBaseBack(3,500,1);
	//moveBaseUntil(44,1000);
	setPositionCB(CHAINBAR_VERTICAL);
	setPositionDR(DOWN_DR);
	setElevation(-15);
	rotateToAngle(51,1000,2,0,1);
	moveBaseWithFactor(32,2000,1);
	setPositionCB(CHAINBAR_DOWN-20);
	setRollers(127);
	setPositionDR(DOWN_DR);
	wait1Msec(600);
	setRollers(10);
	//Mogo
	setPositionCBHappy(CHAINBAR_VERTICAL);
	setChainbar(12);
	rotateToAngle(77,700,4,0,1);
	setPositionMogo(DROP_MOGO);
	moveBaseWithFactor(14,1000,1);
	setPositionMogo(GET_MOGO);
	// Drop first cone
	setRollers(-127,200);
	wait1Msec(100);
	// Second cone
	rotateToAngle(77,700,6,0,1);
	moveBaseBack(14,2000,1);
	rotateToAngle(136,700,2,0,1);
	//rotateToAngle(12,700,2,0,1);
	moveBaseWithFactor(7,2000,1);
	int i;
	for(i=0;i<5;i++){
		getConeFromSide();
		cones++;
	}
	getConeAndHold();
	cones++;
	moveBaseBack(5,2000,1);
	rotateToAngle(236,1000,2,0,1);
	moveBaseWithFactor(39,2000,1)
	rotateToAngle(180,2000,2,0,1);
	setRollers(-10);
	moveBaseWithFactor(25,2000,1);
	setPositionDR(heights[cones] + SIDE_BAR);
	setPositionMogo(VERTICAL_MOGO);
	moveBaseWithFactor(10,1000,1);
	setPositionMogo(DROP_MOGO);
	moveBaseBack(10,1000,1);
	setPositionMogo(VERTICAL_MOGO);
	moveBaseBack(10,1000,1);
	setPositionMogo(DROP_MOGO);
	moveBaseWithFactor(10,1000,1);
}


// Starts Red side to short cones sides
void auto1()
{
	setOffsetAngle(315);
	// Deploy
	setRollers(50);
	wait1Msec(200);
	setPositionDR(MAX_ELEVATION-900);
	setChainbar(-127);
	wait1Msec(700);
	setChainbar(0);
	//setPositionCBHappy(CHAINBAR_HORIZONTAL);
	// Crayola cone
	moveBaseUntil(45,3000);//era 57
	wait1Msec(200);
	setRollers(-127,1000);
	// First cone
	moveBaseBack(3,1000,1);
	//moveBaseUntil(44,1000);
	setPositionCB(CHAINBAR_VERTICAL);
	setPositionDR(DOWN_DR);
	rotateToAngle(375,2000);
	moveBaseWithFactor(31,2000,1);
	setPositionCB(CHAINBAR_DOWN);
	setRollers(127);
	setPositionDR(DOWN_DR);
	wait1Msec(600);
	setRollers(10);
	//Mogo
	setPositionCBHappy(CHAINBAR_VERTICAL);
	setChainbar(12);
	rotateToAngle(384,700);
	setPositionMogo(DROP_MOGO);
	moveBaseWithFactor(13,2000,1);
	wait1Msec(50);
	setPositionMogo(GET_MOGO);
	// Drop first cone
	setRollers(-127,400);
	wait1Msec(100);
	// Second cone
	rotateToAngle(398,700);
	moveBaseBack(11,1000,1);
	wait1Msec(100);
	rotateToAngle(362,2000);
	wait1Msec(100);
	moveBaseWithFactor(5,1000,1);
	setRollers(127);
	setPositionCBHappy(CHAINBAR_DOWN);
	wait1Msec(500);
	setRollers(10);
	triggerHappyAuto();
	// Third cone
	moveBaseWithFactor(6,1000,1);
	setRollers(127);
	setPositionDR(DOWN_DR);
	wait1Msec(400);
	setRollers(10);
	triggerHappyAuto();
	// Fourth cone
	rotateToAngle(362,2000);
	moveBaseWithFactor(9,1000,1);
	setRollers(127);
	setPositionDR(DOWN_DR);
	wait1Msec(400);
	setRollers(10);
	triggerHappyAuto();
	// Fifth cone
	moveBaseWithFactor(6,1000,1);
	setRollers(127);
	setPositionDR(DOWN_DR);
	wait1Msec(400);
	setRollers(10);
	moveBaseBack(5,500,1);
	// triggerHappyAuto(); With arm up
	sonarElevation();
	setPositionCBHappy(CHAINBAR_VERTICAL);
	setChainbar(25);
	wait1Msec(400);
	setRollers(-127, 250);
	wait1Msec(100);//Let the Cone Settle
	// End trigger happy with arm up
	moveBaseBack(57,4000,1);
	rotateToAngle(222,2000);
	moveBaseWithFactor(5,500,1);
	rotateToAngle(138,2000);
	setPositionMogo(VERTICAL_MOGO);
	setMOGOGripper(-30);
	setBase(127);
	wait1Msec(1500);
	setBase(0);
	wait1Msec(100);
	setPositionMogo(VERTICAL_MOGO+700);
	setMOGOGripper(-30);
	setBase(-127);
	wait1Msec(600);
	setBase(0);
}

// Starts Red side to short cones sides
void auto2()
{
	setOffsetAngle(315);
	// Deploy
	setRollers(50);
	wait1Msec(200);
	setPositionDR(MAX_ELEVATION-1000);
	setPositionCBHappy(CHAINBAR_DOWN);
	// Crayola cone
	moveBaseUntil(47,3000);//era 57
	wait1Msec(200);
	setRollers(-127,1000);
	// First cone
	moveBaseBack(3,1000,1);
	//moveBaseUntil(44,1000);
	setPositionCB(CHAINBAR_VERTICAL);
	setPositionDR(DOWN_DR+350);
	rotateToAngle(375,1500);
	moveBaseWithFactor(31,2000,0.75);
	setRollers(127);
	setPositionCB(CHAINBAR_DOWN);
	setPositionDR(DOWN_DR);
	wait1Msec(500);
	setRollers(10);
	//Mogo
	setPositionCBHappy(CHAINBAR_VERTICAL);
	setChainbar(12);
	rotateToAngle(384,700);
	setPositionMogo(DROP_MOGO);
	moveBaseWithFactor(13,1000,1);
	wait1Msec(50);
	setPositionMogo(GET_MOGO);
	// Drop first cone
	setRollers(-127,400);
	wait1Msec(100);
	// Second cone
	rotateToAngle(398,700);
	moveBaseBack(11,1000,1);
	wait1Msec(100);
	rotateToAngle(362,700);
	wait1Msec(100);
	moveBaseWithFactor(5,500,1);
	setRollers(127);
	setPositionCBHappy(CHAINBAR_DOWN);
	setPositionDR(DOWN_DR);
	wait1Msec(500);
	setRollers(10);
	triggerHappyAuto();
	// Third cone
	moveBaseWithFactor(8,500,1);
	setRollers(127);
	setPositionDR(DOWN_DR);
	wait1Msec(500);
	setRollers(10);
	triggerHappyAuto();
	// Fourth cone
	rotateToAngle(362,500);
	moveBaseWithFactor(9,500,1);
	setRollers(127);
	setPositionDR(DOWN_DR);
	wait1Msec(500);
	setRollers(10);
	// triggerHappyAuto(); With arm up
	sonarElevation();
	setPositionCBHappy(CHAINBAR_VERTICAL);
	setChainbar(25);
	wait1Msec(300);
	setRollers(-127, 250);
	wait1Msec(100);//Let the Cone Settle
	// End trigger happy with arm up
	moveBaseBack(55,2500,1);
	rotateToAngle(222,2000);
	moveBaseWithFactor(5,500,1);
	rotateToAngle(138,2000);
	setPositionMogo(VERTICAL_MOGO);
	setMOGOGripper(-30);
	setBase(127);
	wait1Msec(1500);
	setBase(0);
	wait1Msec(100);
	setPositionMogo(VERTICAL_MOGO+700);
	setMOGOGripper(-30);
	setBase(-127);
	wait1Msec(600);
	setBase(0);
}

void auto3()
{
	setOffsetAngle(315);
	// Deploy
	setRollers(50);
	wait1Msec(200);
	setPositionDR(MAX_ELEVATION-900);
	setChainbar(-127);
	wait1Msec(700);
	setChainbar(0);
	//setPositionCBHappy(CHAINBAR_HORIZONTAL);
	// Crayola cone
	moveBaseUntil(45,3000);//era 57
	wait1Msec(200);
	setRollers(-127,1000);
	// First cone
	moveBaseBack(3,1000,1);
	//moveBaseUntil(44,1000);
	setPositionCB(CHAINBAR_VERTICAL);
	setPositionDR(DOWN_DR+350);
	rotateToAngle(376,1500);
	moveBaseWithFactor(31,2000,0.75);
	setPositionCB(CHAINBAR_DOWN);
	setRollers(127);
	wait1Msec(500);
	setRollers(10);
	//Mogo
	setPositionCBHappy(CHAINBAR_VERTICAL);
	setChainbar(12);
	rotateToAngle(384,700);
	setPositionMogo(DROP_MOGO);
	moveBaseWithFactor(13,1000,1);
	wait1Msec(50);
	setPositionMogo(GET_MOGO);
	// Drop first cone
	setRollers(-127,400);
	wait1Msec(100);
	// Second cone
	rotateToAngle(398,700);
	moveBaseBack(11,1000,1);
	wait1Msec(100);
	rotateToAngle(362,700);
	wait1Msec(100);
	moveBaseWithFactor(5,500,1);
	setRollers(127);
	setPositionCBHappy(CHAINBAR_DOWN);
	wait1Msec(500);
	setRollers(10);
	triggerHappyAuto();
	// Third cone
	moveBaseWithFactor(8,500,1);
	setRollers(127);
	setPositionDR(DOWN_DR);
	wait1Msec(500);
	setRollers(10);
	// triggerHappyAuto(); With arm up, no drop
	sonarElevation();
	setPositionCBHappy(CHAINBAR_VERTICAL);
	setChainbar(25);
	wait1Msec(100);//Let the Cone Settle
	// End trigger happy with arm up
	//
	moveBaseBack(45,2500,1);
	rotateToAngle(222,1500);
	moveBaseWithFactor(7,500,1);
	rotateToAngle(133,1000);
	setPositionMogo(VERTICAL_MOGO);
	setMOGOGripper(-15);
	setBase(127);
	wait1Msec(750);
	//setMOGOGripper(127);
	wait1Msec(750);
	setBase(0);
	wait1Msec(100);
	setMOGOGripper(-127);
	setBase(-127);
	wait1Msec(1000);
	setBase(0);
	setPositionMogo(GET_MOGO);
	//Position
	moveBaseWithFactor(10,2000,0.25);
	moveBaseBack(6,500,1);
	rotateToAngle(222,1000);
	moveBaseWithFactor(20,1000,1);
	rotateToAngle(270,1000);
	//Get 2nd MoGo
	setPositionCBHappy(CHAINBAR_VERTICAL);
	setChainbar(12);
	setPositionMogo(DROP_MOGO);
	moveBaseWithFactor(20,2000,1);
	wait1Msec(50);
	setPositionMogo(GET_MOGO);
	//Drop cone
	setRollers(-127,500);
	//Drop MOGO
	moveBaseBack(50,2500,1);
	rotateToAngle(222,1500);
	moveBaseBack(7,500,1);
	rotateToAngle(133,1000);
	setPositionMogo(VERTICAL_MOGO);
	setMOGOGripper(-30);
	setBase(127);
	wait1Msec(750);
	setMOGOGripper(127);
	wait1Msec(750);
	setBase(0);
	wait1Msec(100);
	setMOGOGripper(GET_MOGO);
	setBase(-127);
	wait1Msec(1000);
	setBase(0);
}

// Rojo mirando al lado largo de conos/ Defensa
void auto4()
{
	setOffsetAngle(270);
	setRollers(30);
	//Get 2nd MoGo
	setPositionCBHappy(CHAINBAR_VERTICAL);
	setChainbar(12);
	setPositionMogo(DROP_MOGO);
	moveBaseWithFactor(35,2000,1);
	wait1Msec(50);
	setPositionMogo(GET_MOGO);
	rotateToAngle(270,300);
	//Drop cone
	setRollers(-127,500);

	// Second cone
	moveBaseWithFactor(5,500,1);
	setRollers(127);
	setPositionCBHappy(CHAINBAR_DOWN);
	wait1Msec(500);
	setRollers(10);
	triggerHappyAuto();
	// Third cone
	moveBaseWithFactor(8,500,1);
	setRollers(127);
	setPositionDR(DOWN_DR);
	wait1Msec(500);
	setRollers(10);
	triggerHappyAuto();
	// Fourth cone
	moveBaseWithFactor(8,500,1);
	setRollers(127);
	setPositionDR(DOWN_DR);
	wait1Msec(500);
	setRollers(10);
	moveBaseBack(5,400,1);
	rotateToAngle(270,500);
	// triggerHappyAuto(); With arm up, no drop
	sonarElevation();
	setPositionCBHappy(CHAINBAR_VERTICAL);
	setChainbar(25);
	wait1Msec(100);//Let the Cone Settle
	// End trigger happy with arm up

	//Drop MOGO
	moveBaseBack(45,2500,1);
	rotateToAngle(222,1500);
	moveBaseBack(25,500,1);
	rotateToAngle(133,1000);
	setPositionMogo(VERTICAL_MOGO);
	setMOGOGripper(-30);
	setBase(127);
	wait1Msec(750);
	wait1Msec(750);
	setBase(0);
	wait1Msec(100);
	setPositionMogo(VERTICAL_MOGO+700);
	setMOGOGripper(-30);
	setBase(-127);
	wait1Msec(600);
	setBase(0);

	//Crayola
	setPositionMogo(GET_MOGO);
	rotateToAngle(313,1000);
	setPositionDR(MAX_ELEVATION-900);
	setChainbar(-127);
	wait1Msec(700);
	setChainbar(0);
	//setPositionCBHappy(CHAINBAR_HORIZONTAL);
	// Crayola cone
	moveBaseUntil(45,3000);//era 57
	wait1Msec(200);
	setRollers(-127,1000);

}


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	init();
	startTask(getGyro);
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	auto_test();
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		// Remove this function call once you have "real" code.
		genericControl();
	}
}
