#pragma config(Sensor, in1,    potGripper,     sensorPotentiometer)
#pragma config(Sensor, in2,    potElevation,   sensorPotentiometer)
#pragma config(Sensor, in3,    potChainbar,    sensorPotentiometer)
#pragma config(Sensor, in4,    gyroBase,       sensorGyro)
#pragma config(Sensor, in5,    accBase,        sensorAccelerometer)
#pragma config(Sensor, dgtl1,  encLeft,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encRight,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  baseSonar,      sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  coneSonar,      sensorSONAR_cm)
#pragma config(Motor,  port1,           moGoGripper,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           chainbarLeft,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           elevationLeft, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           elevationRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           chainbarRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           backLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           backRight,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rollers,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define STOP 0
#define CHAINBAR_HORIZONTAL 1465
#define CHAINBAR_VERTICAL 3700
#define MAX_CONE_DISTANCE 30
#define MAX_ELEVATION 3170
#define MAX_CONES 17
#define DOWN 1225

int trigger = 0;
int coneCounter = 4;//Cones that can be managed with chainbar only

void setBase(int speed){
	motor[frontLeft] = speed;
	motor[frontRight] = speed;
	motor[backLeft] = speed;
	motor[backRight] = speed;
}
void setBase(int speedL, int speedR){
	motor[frontLeft] = speedL;
	motor[frontRight] = speedR;
	motor[backLeft] = speedL;
	motor[backRight] = speedR;
}
void rotateBase(int speed){
	setBase(speed, -speed);
}
void setRollers(int speed){
	motor[rollers] = speed;
}
void setRollers(int speed, int time_ms){
	setRollers(speed);
	wait1Msec(time_ms);
	setRollers(STOP);
}
void setMOGOGripper(int speed){
	motor[moGoGripper] = speed;
}
void setElevation(int speed){
	motor[elevationLeft] = speed;
	motor[elevationRight] = speed;
}
void setChainbar(int speed){
	motor[chainbarLeft] = speed;
	motor[chainbarRight]= speed;
}
void moveBase (int distance, int speed) {
	while(SensorValue(encLeft)<distance && SensorValue(encRight)) {
		if(encLeft == encRight) {
			setBase(speed);
		}
		else if(encLeft > encRight){
			setBase(speed*0.90, speed);
		}
		else{
			setBase(speed, speed*0.90);
		}
	}
}

void baseControl(void){
	setBase(vexRT(Ch3) + vexRT(Ch4),vexRT(Ch3) - vexRT(Ch4));
}



void rollerControl(){
	if(vexRT(Btn6U)){
		setRollers(127);
	}
	else if(vexRT(Btn6D)){
		setRollers(-127);
	}
	else{
		setRollers(STOP);
	}
}

void moGoControl(void){
	if(vexRT(Btn8R)){
		setMOGOGripper(80);
	}
	else if(vexRT(Btn8L)){
		setMOGOGripper(-127);
	}
	else{
		setMOGOGripper(STOP);
	}
}

void chainbarHold(void){
	if(SensorValue(potChainbar) > CHAINBAR_HORIZONTAL){
		setChainbar(-20);
	}
	else if(SensorValue(potChainbar) < CHAINBAR_HORIZONTAL){
		setChainbar(20);
	}
	else{
		setChainbar(STOP);
	}
}
void elevationHold(){
	setElevation(17);
}

void elevationControl(void){
	setElevation(vexRT(Ch2));
}

void setPositionCB(int angle){
	while(SensorValue[potChainbar] != angle){
		if(SensorValue(potChainbar)<angle){
			setChainbar(127);
			baseControl();
			elevationControl();
		}
		else if(SensorValue(potChainbar)>angle){
			setChainbar(-127);
			baseControl();
			elevationControl();
		}
	}
	setChainbar(STOP);
	setChainbar(7);
	baseControl();
}

void chainbarControl(){
	if(vexRT(Btn8U)){
		baseControl();
		setPositionCB(CHAINBAR_VERTICAL);
		setChainbar(15);
		setElevation(10);
	}
	else if(vexRT(Btn8D)){
		baseControl();
		setPositionCB(CHAINBAR_HORIZONTAL);
		setChainbar(15);
		setElevation(10);
	}
}

void setPositionDR(int angle){
	while(SensorValue[potElevation]!= angle){
		if(SensorValue(potElevation)<angle){
			setElevation(127);
		}
		else if(SensorValue(potElevation)>angle){
			setElevation(-127);
		}
	}
	elevationHold();
}
bool sonarElevation(void){
	while(SensorValue(coneSonar) < MAX_CONE_DISTANCE){
		// && coneCounter < MAX_CONES-1
		//coneCounter++;
		setElevation(127);
		if(SensorValue(potElevation) > MAX_ELEVATION - 50){//Worst Case
			setElevation(STOP);
			return true;
		}
	}
	elevationHold();
	return false;
}
void triggerHappy(void){
	if(vexRt(Btn5U)){
		setPositionCB(CHAINBAR_HORIZONTAL);
		sonarElevation();
		setPositionCB(CHAINBAR_VERTICAL);
		wait1Msec(400);
		setRollers(-127, 250);
		wait1Msec(100);//Let the Cone Settle
		setPositionCB(CHAINBAR_HORIZONTAL);
		setChainbar(25);
		setPositionDR(DOWN+100);
		wait1Msec(100);
		setChainbar(0);
	}
}

void genericControl(void){
	baseControl();
	elevationControl();
	rollerControl();
	chainbarControl();
	moGoControl();
	triggerHappy();

}
task main()
{

	while(true){

		writeDebugStreamLine("%d\n",SensorValue(potElevation));
		//wait10Msec(25);
		genericControl();
		//trigger = 1;
		//sonarElevation();
	}
}

// Cuanto sube para llegar al poste
// Cuan cerca del poste debe estar (sonar value)

//subir acercar y soltar, regresar
