#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(Sensor, dgtl1,  left,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  right,          sensorQuadEncoder)
#pragma config(Motor,  port2,           left1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           left3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mogoL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mogoR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           right1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           right2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           right3,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../BNSLib.h";
#define CHARS_PER_MESS 8
#define CHARS_PER_VAL 8
#define X_START 0

int rcvChar;
int startChar = 120; // Delimeter for messages char value = 'x'
int encoderR = 0,encoderL = 0, counter = 0;
float x=0, y=0, xr=0, yr=0, xl=0, yl=0, z=0;
bool disableAPS = false; // Make true when you dont want the movement to
// affect position, e.g. when turning.

task aps()
{
	float tempr=0, templ=0, tempz=0, deltar=0, deltal=0, deltaz=0;
	while(true)
	{
		deltar = SensorValue[right] - tempr;
		tempr = SensorValue[right];
		deltal = SensorValue[left] - templ;
		templ = SensorValue[left];

		deltaz = z - tempz;
		tempz = z;

		if(!disableAPS){
			xr += deltar*cosDegrees(z);
			yr += deltar*sinDegrees(z);

			xl += deltal*cosDegrees(z);
			yl += deltar*sinDegrees(z);

			x = (xr + xl)/2;
			y = (yr + yl)/2;
			//writeDebugStreamLine("x=%f, y=%f, angle=%f",x,y,z);
		}

		wait1Msec(1);
	}
}

float getX(char *message){
	char x_str[CHARS_PER_MESS];
	memcpy(x_str, message + X_START + 1 /* Offset */, 8 /* Length */);
	float x = atof(x_str);
	if(message[X_START] == '-') x*=-1;
	return x;
}

task arduinoComm()
{
	char message[CHARS_PER_MESS];

	setBaudRate(uartOne, baudRate115200);

	while (getChar(uartOne) != -1) // Purge existing chars from buffer
	{}

	while (true)
	{
		rcvChar = getChar(uartOne);

		if (rcvChar == -1)
		{
			// No character available

			wait1Msec(2); // Don't want to consume too much CPU time. Waiting eliminates CPU consumption for this task.
			continue;
		}
		if (rcvChar == startChar){
			int charCounter = 0;

			while(charCounter < CHARS_PER_MESS){
				rcvChar = getChar(uartOne);
				if (rcvChar == -1)
				{
					// No character available

					wait1Msec(2); // Don't want to consume too much CPU time. Waiting eliminates CPU consumption for this task.
					continue;
				}
				//writeDebugStream("%c", rcvChar);
				message[charCounter] = (char)rcvChar;
				charCounter++;
			}
			//writeDebugStream("\n");
			z = getX(message);
			writeDebugStreamLine("Angle = %f", z);
		}
	}
	wait1Msec(1);
}

float inchesToTicks (float inches){
	float diameter = 4;
	float ticks;
	ticks = (360.0/(diameter*PI))*inches;
	return ticks;
}

float ticksToInches (float ticks){
	float diameter = 4;
	float inches = 0;
	inches = ((ticks/360)*(diameter*PI));
	return inches;
}


void setBase(int speed){
	motor[left1] = speed;
	motor[left2] = speed;
	motor[left3] = speed;
	motor[right1] = speed;
	motor[right2] = speed;
	motor[right3] = speed;
}

void setBase(int speedR, int speedL){
	motor[left1] = speedL;
	motor[left2] = speedL;
	motor[left3] = speedL;
	motor[right1] = speedR;
	motor[right2] = speedR;
	motor[right3] = speedR;
}


// Stop moving the robot.
void stopBase()
{
	setBase(0);
}

void rotateBase(int speed)
{
	int max = 60;
	if(speed > max)
		speed = max;
	else if(speed < max*-1)
		speed = max*-1;
	setBase(speed, -speed);
}

// Function to move the robot to the front or back.
void moveBase(int speed)
{
	setBase(speed);
}

// Move the base to the front. Request the distance for know how much need to move,
// the variable time is the maximun time for wait to the movement to
// prevent keep going infinitely the task if the robot can´t move and
// finally, the variable factor to reduce the velocity of the robot.
// Note: The distance in inches.
void moveBaseWithFactor(int distance, int time, float factor){
	distance = inchesToTicks(distance);
	writeDebugStreamLine("Start moveBaseFront");
	writeDebugStreamLine("Target distance = %d", distance);
	int encoderAvg = 0;
	encoderR = 0;
	encoderL = 0;
	float initialGyro = z, actualGyro = initialGyro;
	writeDebugStreamLine("Initial Gyro Position = %f", initialGyro);
	int startEncoderValueR = SensorValue[right];
	int startEncoderValueL = SensorValue[left];
	bool atPos=false;
	float pidMovResult;
	//float pidStraightResult;
	counter = 0;

	PID pidMovement;
	//PID pidStraight;
	PIDInit(&pidMovement, 0.3, 0, 1.5); // Set P, I, and D constants
	//PIDInit(&pidStraight, 2, 0, 0.3);//Set constants for driving straight

	clearTimer(T1);
	int timer = T1;
	while(!atPos && timer < time){
		encoderR = (SensorValue[right] - startEncoderValueR);
		encoderL = SensorValue[left] - startEncoderValueL;
		encoderAvg = (encoderR+encoderL)/2;
		writeDebugStreamLine("encR = %d\tencL = %d", encoderR, encoderL);
		pidMovResult = PIDCompute(&pidMovement, distance - encoderAvg);
		//pidStraightResult = PIDCompute(&pidStraight, initialGyro - actualGyro);
		//writeDebugStreamLine("Actual Gyro Position = %f   PID = %f", actualGyro, pidStraightResult);
		moveBase(pidMovResult);
		if (abs(encoderAvg-distance)<2)
			counter++;
		if (counter >= 4)
			atPos = true;
		timer = time1[T1];
		wait1Msec(25);
		actualGyro = z;
	}
	moveBase(0);
	writeDebugStreamLine("Encoder at position = %d", encoderAvg);
}

// Rotate the base to one side. The variable time is the maximun time for wait to the rotation to
// prevent keep going infinitely the task if the robot can´t rotate.
// The variable angle is for the finally wanted angle.
void rotateToAngle(float targetAngle, int time){
	writeDebugStreamLine("Start rotateToAngle");
	writeDebugStreamLine("Target angle = %f", targetAngle);
	bool atGyro=false, isCW=false;
	float pidGyroResult;
	counter = 0;

	// Change negative target angle to 0-360 range
	if(targetAngle < 0){
		targetAngle = 360 + targetAngle;
	}

	if(targetAngle < z){
		isCW=true;
	}

	// PID Constant cases
	PID pidGyro;
	PIDInit(&pidGyro, 5, 0, 0); // Set P, I, and D constants

	clearTimer(T1);
	while(!atGyro && time1[T1] < time){
		writeDebugStreamLine("Current angle = %f", z);

		// Calculate error
		float error = targetAngle - z;
		if(error > 180){
			error = 360 - error;
		}
		else if(error < -180){
			error = -360 - error;
		}
		writeDebugStreamLine("error=%f",error);
		// Compute PID
		pidGyroResult = PIDCompute(&pidGyro, error);

		// Decide if rotation is CW or CCW
		rotateBase(pidGyroResult);

		// Condition to end
		if (abs(z-targetAngle)<0.2)
			counter++;
		if (counter > 10)
			atGyro = true;
		wait1Msec(1);
	}
	writeDebugStreamLine("Final angle = %f", z);
	stopBase();
}

void moveTo (int newX, int newY){//Recieves values in inches
	float targetAngle=0;
	int magnitude;
	float dx, dy;

	//Calculate Angle and Magnitude
	newX=inchesToTicks(newX);
	newY=inchesToTicks(newY);

	dx = newX-x;
	dy = newY-y;

	writeDebugStreamLine("x = %d, y = %d", x, y);
	writeDebugStreamLine("Target x = %d, Target y = %d", newX, newY);

	if (dx!=0 && dy!=0)
		targetAngle = radiansToDegrees(atan2(dy,dx));
	else
		targetAngle = z;

	//Move Robot
	rotateToAngle(targetAngle,500);
	magnitude = sqrt(((dx)*(dx)) + ((dy)*(dy)));
	wait1Msec(2000);//Remove once PID is done
	moveBaseWithFactor(magnitude,2000,75);//TODO, change with PID

}

void initializeSensors (){
	//Initialize Encoders
	SensorValue[right] = 0;
	SensorValue[left] = 0;
	//End Initialize Encoder
}


task main()
{
	BNS();
	initializeSensors();
	//startTask(aps);
	startTask(arduinoComm);
	//rotateToAngle(90,2000);
	//moveTo(0,0);
	/*setBase(60);
	wait1Msec(500);
	setBase(0);
	/*wait1Msec(500);
	setBase(-60);
	wait1Msec(500);
	setBase(0);
	*/
	while(1){wait10Msec(1);}
}
