#pragma config(Sensor, in1,    gyroBase,       sensorGyro)
#pragma config(Sensor, in2,    potGripper,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  encLeft,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encRight,       sensorQuadEncoder)
#pragma config(Motor,  port2,           left1,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           left2,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           left3,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           mogoL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mogoR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           right1,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           right2,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           right3,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//*********************************************************************************************
//			Includes
//*********************************************************************************************

#include "../BNSLib.h";

#define STOP 0
#define DROP_MOGO 2100
#define GET_MOGO 460
#define VERTICAL_MOGO 1200

//*********************************************************************************************
//			Setters
//*********************************************************************************************

void setBase(int speed){
		motor[left1] = speed;
		motor[left2] = speed;
		motor[left3] = speed;
		motor[right1] = speed;
		motor[right2] = speed;
		motor[right3] = speed;
}

void setBase(int speedR, int speedL){
		motor[left1] = speedL;
		motor[left2] = speedL;
		motor[left3] = speedL;
		motor[right1] = speedR;
		motor[right2] = speedR;
		motor[right3] = speedR;
}

void setMOGOGripper(int speed){
	motor[mogoL] = speed;
	motor[mogoR] = speed;
}

//*********************************************************************************************
//			Base Functions
//*********************************************************************************************

// This variables for the ecnoders and counter fore the PID.
int encoderL, encoderR, counter;

// Function to move the robot to the front or back.
void moveBase(int speed)
{
	setBase(speed);
}

// Rotate the base clockwise or counter-clockwise.
void rotateBase(int speed)
{
	setBase(speed, -speed);
}

// Stop moving the robot.
void stopBase()
{
	setBase(0);
}

// Convert the distance of ticks (the value of the encoder) in inches.
float ticksToInches(int ticks)
{
	float inches = ticks*((2.75*PI)/360.0)/0.9;
	return inches;
}

float inchesToTicks(int inches)
{
	float ticks = inches*(360.0/(2.75*PI))*0.9;
	return ticks;
}


// Move the base to the front. Request the distance for know how much need to move,
// the variable time is the maximun time for wait to the movement to
// prevent keep going infinitely the task if the robot can´t move and
// finally, the variable factor to reduce the velocity of the robot.
// Note: The distance in inches.
void moveBaseWithFactor(int distance, int time, float factor){
	distance = inchesToTicks(distance);
	writeDebugStreamLine("Start moveBaseFront");
	writeDebugStreamLine("Target distance = %d", distance);
	int encoderAvg = 0;
	encoderR = 0;
	encoderL = 0;
	float initialGyro = SensorValue[gyroBase], actualGyro = initialGyro;
	writeDebugStreamLine("Initial Gyro Position = %f", initialGyro);
	int startEncoderValueR = SensorValue[encRight];
	int startEncoderValueL = SensorValue[encLeft];
	bool atPos=false;
	float pidMovResult;
	//float pidStraightResult;
	counter = 0;

	PID pidMovement;
	//PID pidStraight;
	PIDInit(&pidMovement, 0.3, 0, 1.5); // Set P, I, and D constants
	//PIDInit(&pidStraight, 2, 0, 0.3);//Set constants for driving straight

	clearTimer(T1);
	int timer = T1;
	while(!atPos && timer < time){
		encoderR = (SensorValue[encRight] - startEncoderValueR);
		encoderL = SensorValue[encLeft] - startEncoderValueL;
		encoderAvg = (encoderR+encoderL)/2;
		writeDebugStreamLine("encR = %d\tencL = %d", encoderR, encoderL);
		pidMovResult = PIDCompute(&pidMovement, distance - encoderAvg);
		//pidStraightResult = PIDCompute(&pidStraight, initialGyro - actualGyro);
		//writeDebugStreamLine("Actual Gyro Position = %f   PID = %f", actualGyro, pidStraightResult);
		moveBase(pidMovResult);
		if (abs(encoderAvg-distance)<2)
			counter++;
		if (counter >= 4)
			atPos = true;
		timer = time1[T1];
		wait1Msec(25);
		actualGyro = SensorValue[gyroBase];
	}
	moveBase(0);
	writeDebugStreamLine("Encoder at position = %d", encoderAvg);
}

// Move the base to the back. Request the distance for know how much need to move,
// the variable time is the maximun time for wait to the movement to
// prevent keep going infinitely the task if the robot can´t move and
// finally, the variable factor to reduce the velocity of the robot.
// Note: The distance in inches.
void moveBaseBack(int distance, int time, int slowFactor)
{
	distance = inchesToTicks(distance);

	writeDebugStreamLine("Start moveBaseFront");
	writeDebugStreamLine("Target distance = %d", distance);

	int encoderAvg = 0;
	encoderR = 0;
	encoderL = 0;
	int startEncoderValueR = SensorValue[encRight];
	int startEncoderValueL = SensorValue[encLeft];
	bool atPos=false;
	float pidMovResult, pidStraightResult;
	counter = 0;

	PID pidMovement;
	//PID pidStraight;
	PIDInit(&pidMovement, 0.3, 0, 1.5); // Set P, I, and D constants
	//PIDInit(&pidStraight, 0.5, 0, 0);//Set constants for driving straight

	clearTimer(T1);
	int timer = T1;

	while(!atPos && timer < time)
	{
		encoderR = abs(SensorValue[encRight] - startEncoderValueR);
		encoderL = abs(SensorValue[encLeft] - startEncoderValueL);
		writeDebugStreamLine("encoder derecho = %d", encoderR);
		writeDebugStreamLine("encoder izquierdo = %d", encoderL);
		encoderAvg = (encoderR+encoderL)/2;
		pidMovResult = PIDCompute(&pidMovement, distance - encoderAvg);
		//pidStraightResult = PIDCompute(&pidStraight, encoderL - encoderR);
		pidMovResult = pidMovResult >  127 ? 127 : pidMovResult;

		moveBase(-pidMovResult);

		if (abs(encoderAvg-distance)<2)
			counter++;
		if (counter >= 4)
			atPos = true;
		timer = time1[T1];
		wait1Msec(25);
	}
	stopBase();
	writeDebugStreamLine("Encoder at position = %d", encoderAvg);
}

// Default values for configure the gyro.
float gyroAngle;
int offsetAngle = 90;

// Configure the default values of the gyro.
void setOffsetAngle (int angle){
	offsetAngle = angle;
}

// Task for get the value of the gyro
task getGyro {
	while(1){
		gyroAngle = (SensorValue[gyroBase]/10.0 + offsetAngle);//Offset can be changed with function.
		//writeDebugStreamLine("gyro = %d", gyroAngle);
		wait1Msec(25);																	 //Default is 90.
	}
}

// Rotate the base to one side. The variable time is the maximun time for wait to the rotation to
// prevent keep going infinitely the task if the robot can´t rotate.
// The variable angle is for the finally wanted angle.
void rotateToAngle(float targetAngle, int time){
	writeDebugStreamLine("Start rotateToAngle");
	writeDebugStreamLine("Target angle = %f", targetAngle);
	bool atGyro=false;
	float pidGyroResult;
	counter = 0;

	PID pidGyro;
	PIDInit(&pidGyro, 0.25, 0, 1.8); // Set P, I, and D constants

	clearTimer(T1);
	int timer = time1[T1];
	while(!atGyro && timer < time){
		writeDebugStreamLine("Current angle = %f", gyroAngle);
		pidGyroResult = PIDCompute(&pidGyro, targetAngle - gyroAngle);
		rotateBase(18*pidGyroResult);
		if (abs(gyroAngle-targetAngle)<0.1)
			counter++;
		if (counter > 10)
			atGyro = true;
		timer = time1[T1];
		wait1Msec(20);
	}
	stopBase();
}

// Rotate the base to one side. The variable time is the maximun time for wait to the rotation to
// prevent keep going infinitely the task if the robot can´t rotate.
// The variable angle is for the amount of angle to rotate.
void rotateThisAngle(float angle, int time){
	writeDebugStreamLine("Start rotateThisAngle");
	writeDebugStreamLine("Target angle = %f", angle);
	bool atGyro = false;
	float pidGyroResult;
	counter = 0;

	PID pidGyro;
	PIDInit(&pidGyro, 0.3, 0, 0.4); // Set P, I, and D constants

	angle = (gyroAngle + angle)%360;

	clearTimer(T1);
	int timer = time1[T1];
	while(!atGyro && timer < time){
		pidGyroResult = PIDCompute(&pidGyro, angle - gyroAngle);
		rotateBase(15*pidGyroResult);
		if (abs(gyroAngle-angle)<2)
			counter++;
		if (counter > 3)
			atGyro = true;
		timer = time1[T1];
		wait1Msec(20);
	}
	stopBase();
}

void genericControl(void){
	motor[left1] = vexRT[Ch3] + vexRT[Ch4];
	motor[left2] = vexRT[Ch3] + vexRT[Ch4];
	motor[left3] = vexRT[Ch3] + vexRT[Ch4];
	motor[right1] = vexRT[Ch3] - vexRT[Ch4];
	motor[right2] = vexRT[Ch3] - vexRT[Ch4];
	motor[right3] = vexRT[Ch3] - vexRT[Ch4];
	if (vexRT[Btn8R]){
		motor[mogoL] = 127;
		motor[mogoR] = 127;
	}
	else if (vexRT[Btn8L]){
		motor[mogoL] = -127;
		motor[mogoR] = -127;
	}
	else{
		motor[mogoL] = 0;
		motor[mogoR] = 0;
	}
}

void setPositionMogo(int angle){
	clearTimer(T2);
	if(SensorValue[potGripper] < angle)
	{
		while(SensorValue[potGripper] < angle && time1(T2) < 4000)
		{
			setMOGOGripper(127);
		}
	}
	else
	{
		while(SensorValue(potGripper)>angle && time1(T2) < 4000)
		{
			setMOGOGripper(-127);
		}
	}
	setMOGOGripper(0);
}

void init()
{
	BNS();

	//Initialize Gyro
	SensorType[gyroBase] = sensorNone;
	wait1Msec(1000);
	SensorType[gyroBase] = sensorGyro;
	wait1Msec(2000);
	//End Initialize Gyro

	SensorValue[encRight] = 0;
	SensorValue[encLeft] = 0;

	startTask(getGyro);

	clearDebugStream();
}

void progSkills()
{
	setOffsetAngle(90);
	setPositionMogo(DROP_MOGO);
	moveBaseWithFactor(20,2000,1);
	setPositionMogo(GET_MOGO);
	rotateToAngle(90,600);
	moveBaseWithFactor(5,1000,1);
	rotateToAngle(180, 1000);
	wait1Msec(200);
	moveBaseWithFactor(5,1000,1);
	wait1Msec(200);
	rotateToAngle(90,2000);
	setPositionMogo(VERTICAL_MOGO);
	setMOGOGripper(-15);
	moveBaseWithFactor(15,700,1);
	setPositionMogo(VERTICAL_MOGO+700);
	setMOGOGripper(0);
	rotateToAngle(90,3000);
	moveBaseBack(20,2000,1);
	setPositionMogo(GET_MOGO);
	rotateToAngle(180, 1500);
	wait1Msec(200);
	moveBaseWithFactor(7,1000,1);//UUUUUUUUGGGGGGHHHH
	wait1Msec(200);
	rotateToAngle(274,1000);
	//Repeat
	moveBase(-50);
	wait1Msec(750);
	moveBase(0);
	setPositionMogo(DROP_MOGO);
	moveBaseWithFactor(20,2000,1);
	setPositionMogo(GET_MOGO);
	moveBaseWithFactor(10,1000,1);
	rotateToAngle(360, 1000);
	moveBaseWithFactor(6,1000,1);
	rotateToAngle(270,2000);
	setPositionMogo(VERTICAL_MOGO);
	setMOGOGripper(-15);
	moveBaseWithFactor(15,700,1);
	setPositionMogo(VERTICAL_MOGO+700);
	setMOGOGripper(0);
	moveBaseBack(20,2000,1);
	setPositionMogo(GET_MOGO);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = false;
	init();
	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	progSkills();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  while (true)
  {
		genericControl();
  }
}
